Modifications Page de contribution
Tariha/xassida.sn-fontend pull request #3
Opened 2023-08-16 20:14 UTC by dmd99

### 1. Config:
   nous avous modifié ```config/pages.tsx``` pour y ajouter un objet **contribute** qui va sotcker les variables title et subtitle de 
   notre page contribute
___
### 2. constants: 
 Nous avons créer et typé plusieurs variables dans ```lib/constants.ts``` , leurs types sonts enregistrés dans le nouveau fichier ```types/donations.ts``` . Ces variables nous seront utiles tout au long de la construction de notre travail et leur déclaraation centralisé nous facilitera la tache an cas de modifications
___
### 3. Core modifs:
un seul fichier core a été modifier: ```components/Navbar/NavigationDrawer/DonationCard.tsx``` afin de rendre fonctionnel le button avec next-link
___
### 4. Nous avons creer le sous-répertoire suivant dans  le répertoire ```app```
```
📦contribute
 ┣ 📂components
 ┃ ┣ 📂contribution
 ┃ ┃ ┣ 📜DonationFrequency.tsx
 ┃ ┃ ┣ 📜DonationTile.tsx
 ┃ ┃ ┣ 📜DonationType.tsx
 ┃ ┃ ┗ 📜PaymentOptions.tsx
 ┃ ┣ 📂contributor _(vide pour le moment)_
 ┃ ┗ 📂core
 ┃ ┃ ┣ 📜QuestionCard.tsx
 ┃ ┃ ┗ 📜TitleTile.tsx
 ┗ 📜page.tsx
```
Dans le tout il n'y a que des composantsn front de bases qui ne perturberons pas le fonstionnement de l'application

2023-08-16 22:58 UTC, Linzo99 requested changes
### Utiliser les composants shadcn/ui
S'assurer d'utiliser les composants shadcn/ui dès possible afin d'éviter de récréer la roue.

### Lint, Format et Typecheck
S'assurer que le code est bien formatter.
Avant chaque PR executer ces commandes
```bash
npm run lint:fix
npm run format:write
npm run typecheck
```

**NB:** Bien gérer la responsivité

2023-08-16 22:58 UTC, Linzo99 commented on app/contribute/components/contribution/DonationTile.tsx
> +const DonationTypes = ({handleDonationType}:TypeProps) => {
Serait préférable d'utiliser des Tabs, tu peux voir sur shadcn/ui

2023-08-16 22:58 UTC, Linzo99 commented on app/contribute/components/contribution/DonationTile.tsx
> +        <form>
Pour le formulaire, utiliser les Form shadcn/ui

2023-08-16 22:58 UTC, Linzo99 commented on app/contribute/components/contribution/PaymentOptions.tsx
> +function PaymentOptions({ amounts, frequency }: Props) {
Un Radio Group, permettrait de faire abstraction.

2023-08-16 22:58 UTC, Linzo99 commented on app/contribute/components/core/TitleTile.tsx
> +const TitleTile = ({ title, subtitle }: Props) => {
Tu pouvais utiliser le component **Card** de @/components/ui/card

2023-08-16 22:58 UTC, Linzo99 commented on app/contribute/page.tsx
> +        <div className="flex gap-8 p-4">
Je pense que c'est plus adapté d'utilisé comme **display** un **grid**

2023-08-17 00:06 UTC, dmd99 commented on app/contribute/components/contribution/DonationTile.tsx
> +const DonationTypes = ({handleDonationType}:TypeProps) => {
Si on a deux tabs on aura quasi le même contenu dans les deux tabs, raison pour laquelle j'ai évité les tabs de la library shadcn-ui

2023-08-17 00:07 UTC, dmd99 commented on app/contribute/components/contribution/PaymentOptions.tsx
> +function PaymentOptions({ amounts, frequency }: Props) {
Bien vu 👍

2023-08-17 00:15 UTC, dmd99 commented
Vos reviews seront pris en compte pour le prochain PR. Merci

2023-08-22 13:13 UTC, Linzo99 requested changes
Du très bon travail, j'apprécie beaucoup le temps et l'effort dispensé.

Je t'encourage à visiter ce code pour voir un exemple d'utilisation du component Form. Cela peut aider à améliorer le code:
https://github.com/Tariha/xassida.sn-fontend/blob/feature/audio/app/(admin)/dashboard/audios/components/AudioModalForm/AudioForm.tsx

2023-08-22 13:13 UTC, Linzo99 commented on config/pages.ts
> +    "<strong>Tout don que vous ferez par charité vous sera remplacé par votre Seigneur,\
Un moyen de ne pas utiliser du HTML dans le texte ? C'est préférable

2023-08-22 13:13 UTC, Linzo99 commented on lib/utils.ts
> +export function extractZodValuesForTypes() {
C'est pas plus facile d'énumérer les Types, vu qu'il y en a juste 2 ?

2023-08-22 13:13 UTC, Linzo99 commented on app/contribute/components/contribution/DonationType.tsx
> +const DonationTypes = ({ types, handleDonationType }: TypeProps) => {
Préférable d'avoir le même nom que le fichier.

2023-08-22 13:13 UTC, Linzo99 commented on app/contribute/components/contribution/DonationFrequency.tsx
> +  frequencies: IDonationFrequency[]
Importer les fréquences au lieu de le passer en props. Cela permettrait de rendre le component un peu plus indépendant

2023-08-22 15:09 UTC, dmd99 commented on config/pages.ts
> +    "<strong>Tout don que vous ferez par charité vous sera remplacé par votre Seigneur,\
Je vais me pencher sur la question pour voir la soltion qui sera la plus adaptée

2023-08-22 15:09 UTC, dmd99 commented on lib/utils.ts
> +export function extractZodValuesForTypes() {
Le type ```string[]``` n'est pas assignable au type cible ```[string, ...string[]]```. Par conséquent la source founit ne correspondra pas à l'élement requis à la position [0] de la cible raison pour laquelle j'ai contourné le problème de cette façon.

2023-08-22 15:16 UTC, dmd99 commented
Je suis ravi que mon assistance vous soit utile. Votre retour est très apprécié.

Je prends note de votre suggestion concernant le composant Form et j'irai certainement jeter un coup d'œil pour comprendre comment il est utilisé dans le code. De base je suis en front j'utilise Vuejs/Nuxt, donc contribuer à ce projet me permet de m'ameliorer sur cette technologie avec des exemples concret et des fonctionnalités avancées ainsi c'est à moi de vous remercier. N'hésitez donc surtout pas à me faire part de la moindre remarque.

2024-01-09 09:59 UTC, closed without merging